# Site settings
title: Computational Problem Solving & Software Development
description: "A computing course in DCU for applicants with a prior knowledge of programming."
url: "http://cpssd.net"
author:
  name: "Noah Ã“ Donnaile"
  email: "cac@redbrick.dcu.ie"
  url: "http://mycode.doesnot.run"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0"

# Plugins
gems: ["jekyll-paginate"]

# Options
custom_header: false
custom_nav_footer: false
reverse: false
