baseURL: https://cpssd.net
languageCode: en-ie
title: The Unofficial CPSSD Homepage
theme: cpssd
params:
  description: |
    Computational Problem Solving and Software Development (CPSSD) is an
    undergraduate computing course in Dublin City University. It is aimed at
    applicants with prior programming experience, and is generally the hippest
    place to be this side of Ballymaloe.
  links:
    - name: Learn More
      location: /about
    - name: Students
      location: /students
